spring.application.name=synergy-next30-core

gw.base-url=https://gw.dongamedia.com
gw.hash-key=79007189296633872192398228345530954072110613
gw.access-token=mwABnLttSwfcVUrhQJvRTvsQOpU069
gw.group-seq=gcmsAmaranth29108

#PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/synergy_core
spring.datasource.username=root
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#JPA ?? ??? ??
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

